spring.application.name=SistemaSeguimientoDocumentosAPI

#spring.jpa.database=POSTGRESQL
#spring.sql.init.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/db_sistema_seguimiento_documentos
spring.datasource.username=mrdevv
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.servlet.context-path=/api/v1

spring.jackson.time-zone=America/Lima

spring.jpa.show-sql=true