CREATE DATABASE db_sistema_seguimiento_documentos;

USE db_sistema_seguimiento_documentos;

CREATE TABLE MAE_ROL(
	ROL_ID INT NOT NULL AUTO_INCREMENT,
    DESCRIPCION VARCHAR(50) NOT NULL UNIQUE,
    PRIMARY KEY(ROL_ID)
);

CREATE TABLE MAE_TIPO_DOCUMENTO(
	TIPO_DOCUMENTO_ID INT NOT NULL AUTO_INCREMENT,
    DESCRIPCION VARCHAR(100) NOT NULL UNIQUE,
    PRIMARY KEY(TIPO_DOCUMENTO_ID)
);

CREATE TABLE MAE_DOCUMENTO_ESTADO(
	DOCUMENTO_ESTADO_ID INT NOT NULL,
    DESCRIPCION VARCHAR(30) NOT NULL UNIQUE,
    PRIMARY KEY(DOCUMENTO_ESTADO_ID)
);

CREATE TABLE MAE_INDICACION(
	INDICACION_ID INT NOT NULL,
    DESCRIPCION VARCHAR(100) NOT NULL UNIQUE,
    PRIMARY KEY(INDICACION_ID)
);

CREATE TABLE MAE_AREA(
	AREA_ID INT NOT NULL AUTO_INCREMENT,
    DESCRIPCION VARCHAR(200) NOT NULL UNIQUE,
    ESTADO TINYINT NOT NULL DEFAULT 1,
    PRIMARY KEY(AREA_ID)
);

CREATE TABLE MAE_PERSONA(
	PERSONA_ID INT NOT NULL AUTO_INCREMENT,
    NOMBRES VARCHAR(45) NOT NULL,
    APELLIDOS VARCHAR(45) NOT NULL,
    DNI VARCHAR(8) NOT NULL UNIQUE,
    CELULAR VARCHAR(9),
    PRIMARY KEY(PERSONA_ID)
);

CREATE TABLE MAE_USUARIO(
	USUARIO_ID INT NOT NULL AUTO_INCREMENT,
    PERSONA_ID INT NOT NULL UNIQUE,
    ROL_ID INT NOT NULL,
    NOMBRE_USUARIO VARCHAR(10) NOT NULL UNIQUE,
    PASSWORD VARCHAR(50) NOT NULL,
    ESTADO TINYINT NOT NULL DEFAULT 1,
    PRIMARY KEY(USUARIO_ID),
    FOREIGN KEY(PERSONA_ID) REFERENCES MAE_PERSONA(PERSONA_ID),
	FOREIGN KEY(ROL_ID) REFERENCES MAE_ROL(ROL_ID)
);

CREATE TABLE TRD_USUARIO_AREA(
	USUARIO_AREA_ID INT NOT NULL AUTO_INCREMENT,
    USUARIO_ID INT NOT NULL,
    AREA_ID INT NOT NULL,
    FECHA_INGRESO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_SALIDA DATETIME,
    ESTADO CHAR NOT NULL DEFAULT 'a',
    PRIMARY KEY(USUARIO_AREA_ID),
    FOREIGN KEY(USUARIO_ID) REFERENCES MAE_USUARIO(USUARIO_ID),
    FOREIGN KEY(AREA_ID) REFERENCES MAE_AREA(AREA_ID)
);

CREATE TABLE MAE_DOCUMENTO(
	DOCUMENTO_ID INT NOT NULL AUTO_INCREMENT,
    TIPO_DOCUMENTO_ID INT NOT NULL,
    USUARIO_AREA_ID INT NOT NULL,
    NUMERO_DOCUMENTO VARCHAR(45) NOT NULL UNIQUE,
    ASUNTO VARCHAR(255) NOT NULL,
    FOLIOS INT NOT NULL,
    FECHA_REGISTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DOCUMENTO_ESTADO_ID INT NOT NULL,
    PRIMARY KEY(DOCUMENTO_ID),
    FOREIGN KEY(TIPO_DOCUMENTO_ID) REFERENCES MAE_TIPO_DOCUMENTO(TIPO_DOCUMENTO_ID),
    FOREIGN KEY(USUARIO_AREA_ID) REFERENCES TRD_USUARIO_AREA(USUARIO_AREA_ID),
	FOREIGN KEY(DOCUMENTO_ESTADO_ID) REFERENCES MAE_DOCUMENTO_ESTADO(DOCUMENTO_ESTADO_ID)
);

CREATE TABLE TRS_ENVIO(
	ENVIO_ID INT NOT NULL AUTO_INCREMENT,
    DOCUMENTO_ID INT NOT NULL,
    USUARIO_AREA_ORIGEN_ID INT NOT NULL,
    USUARIO_AREA_DESTINO_ID INT NOT NULL,
    INDICACION_ID INT NOT NULL,
    FOLIOS INT NOT NULL,
    OBSERVACION TEXT,
    FECHA_ENVIO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DOCUMENTO_ESTADO_ID INT NOT NULL,
	PRIMARY KEY(ENVIO_ID),
    FOREIGN KEY(DOCUMENTO_ID) REFERENCES MAE_DOCUMENTO(DOCUMENTO_ID),
    FOREIGN KEY(USUARIO_AREA_ORIGEN_ID) REFERENCES TRD_USUARIO_AREA(USUARIO_AREA_ID),
	FOREIGN KEY(USUARIO_AREA_DESTINO_ID) REFERENCES TRD_USUARIO_AREA(USUARIO_AREA_ID),
	FOREIGN KEY(INDICACION_ID) REFERENCES MAE_INDICACION(INDICACION_ID),
	FOREIGN KEY(DOCUMENTO_ESTADO_ID) REFERENCES MAE_DOCUMENTO_ESTADO(DOCUMENTO_ESTADO_ID)    
);

CREATE TABLE TRS_RECEPCION(
	RECEPCION_ID INT NOT NULL AUTO_INCREMENT,
    ENVIO_ID INT NOT NULL,
    USUARIO_AREA_ID INT NOT NULL,
    FECHA_RECEPCION DATETIME,
    DOCUMENTO_ESTADO_ID INT NOT NULL,
	PRIMARY KEY(RECEPCION_ID),
    FOREIGN KEY(ENVIO_ID) REFERENCES TRS_ENVIO(ENVIO_ID),
    FOREIGN KEY(USUARIO_AREA_ID) REFERENCES TRD_USUARIO_AREA(USUARIO_AREA_ID),
	FOREIGN KEY(DOCUMENTO_ESTADO_ID) REFERENCES MAE_DOCUMENTO_ESTADO(DOCUMENTO_ESTADO_ID)    
);




