DELIMITER //
CREATE PROCEDURE sp_listar_usuarios_area(
)
BEGIN
	SELECT 
    UA.USUARIO_AREA_ID, 
    UA.FECHA_INGRESO,     
    A.DESCRIPCION,     
    U.USUARIO_ID, U.NOMBRE_USUARIO AS USER,
    P.PERSONA_ID, P.NOMBRES, P.APELLIDOS, P.DNI, P.CELULAR,
    R.ROL_ID, R.DESCRIPCION,
    UA.ESTADO
    FROM TRD_USUARIO_AREA UA
    INNER JOIN MAE_AREA A ON UA.AREA_ID = A.AREA_ID
    INNER JOIN MAE_USUARIO U ON UA.USUARIO_ID = U.USUARIO_ID
    INNER JOIN MAE_PERSONA P ON U.PERSONA_ID = P.PERSONA_ID
    INNER JOIN MAE_ROL R ON U.ROL_ID = R.ROL_ID;
END //
DELIMITER ;